# Generated by Django 4.1.5 on 2023-09-12 10:06

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("socialapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": [],},
            bases=("socialapp.user",),
            managers=[("objects", django.contrib.auth.models.UserManager()),],
        ),
    ]
